theme = "hugo-resume"
baseURL = "https://www.russellrosario.com/"
languageCode = "en-us"
title = "Russell Rosario - Accountant & Developer"

[params]
    firstName = "Russell"
    lastName = "Rosario"
    address = "Miami, FL"
    phone = "1-305-803-8555"
    contactNote = "Dev Tools Engineer" #used in QR code only
    profileImage = "img/profile.jpg"
    email = "rosariorussell@gmail.com"
    description = "Senior level accountant and software engineer experienced with organizing teams, managing budgets, financial reporting, process automation, data analytics, and JavaScript/Node solutions on AWS cloud infrastructure."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showBlogs = true
    showPortfolio = true
    showExperience = true
    showEducation = true

		showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/rosariorussell/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/rosariorussell/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/russellrosario"

[params.google.analytics]
    trackerID = "UA-93956182-1"

[outputs] #only required for search
    home = ["HTML", "JSON"]
