theme = "hugo-resume"
baseURL = "https://www.russellrosario.com/"
languageCode = "en-us"
title = "Russell Rosario - Accountant & Developer"

[params]
    firstName = "Russell"
    lastName = "Rosario"
    address = "Miami, FL"
    phone = "1-937-303-8257"
    contactNote = "Dev Tools Engineer" #used in QR code only
    profileImage = "img/profile.jpg"
    email = "rosariorussell@gmail.com"
    description = "Accountant & Software Engineer"
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showBlogs = true
    showPortfolio = true
    showExperience = false
    showEducation = false

		showQr = false

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/russellrosario/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/russellrosario/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/russellrosario"

[[params.handles]]
    name = "AngelList"
    link = "https://angel.co/russellrosario"

[params.google.analytics]
    trackerID = "UA-93956182-1"

[outputs] #only required for search
    home = ["HTML", "JSON"]

[markup.goldmark.renderer]
    unsafe = true